Hello world
go-park-mail-ru/2019_2_Pirogi pull request #1
Opened 2019-09-26 11:09 UTC by Artefakt-ff

Кирилл, посмотри layout плз

2019-09-26 14:36 UTC, Smet1 commented
go modules

2019-09-26 14:39 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +		log.Fatal(err)
фаталы могут быть только в main.go

2019-09-26 15:05 UTC, Smet1 requested changes

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +	if u, ok := in.(user.User); ok {
ты не сможешь обновить истекающую сессию

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +func (db *DB) Get(id int, t string) (interface{}, error) {
зачем пустой интерфейс

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +	oleg, _ := user.CreateUser(1, "oleg@mail.ru", "Oleg", user.GetMD5Hash("qwerty123"), "oleg.jpg", 7.3)
почему игнор ошибки?

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/user/user.go
> +	"errors"
если ты на 12 го, то посмотри пакет pkg/errors

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/validators/main.go
> +var emailPattern = regexp.MustCompile(`^([a-z0-9_-]+\.)*[a-z0-9_-]+@[a-z0-9_-]+(\.[a-z0-9_-]+)*\.[a-z]{2,6}$`)
я не очень за такие переменные, если это не тесты.
Сделай объект, внутри него лежит эта регулярка. На нем пишешь методы и их дергаешь

2019-09-26 15:05 UTC, Smet1 commented on internal/app/server/main.go
> +package server
тут не может быть main.go
переименуй файл

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +package handlers
еще один main.go

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +package inmemory
еще один main.go

2019-09-26 15:05 UTC, Smet1 commented on cmd/server/main.go
> +	"../../internal/app/server"
отписал, в мр коммент по модулям
https://habr.com/ru/post/421411/
https://github.com/golang/go/wiki/Modules

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +func HandleUsers(w http.ResponseWriter, r *http.Request) {
Сделай функцию типа GetHandlerUsers, которая принимает в себя объекты, с которыми ты будешь работать, например, коннект к базе. Должна возвращать http.HandleFunc

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +		return nil, errors.New("no user with id: " + strconv.Itoa(id))
используй врапы pkg errors

2019-09-26 15:05 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +func main() {
удоли

2019-09-26 15:07 UTC, Smet1 commented on internal/pkg/inmemory/main.go
> +		return nil, errors.New("no user with id: " + strconv.Itoa(id))
https://godoc.org/github.com/pkg/errors

2019-09-26 15:07 UTC, Smet1 commented on internal/pkg/user/user.go
> +	"errors"
https://godoc.org/github.com/pkg/errors

2019-09-28 16:03 UTC, Smet1 requested changes

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/auth/main.go
> +			return errors.New("db error while inserting cookie: " + err.Error())
errors.Wrap

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/auth/main.go
> +	isAuth := err != http.ErrNoCookie
зачем

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/auth/main.go
> +	isAuth := err != http.ErrNoCookie
зачем x2

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/error/main.go
> +	return "{\"error\":\"" + s + "\"}\n"
мне не очень это нравится, почему не использовать структуру и маршаллить ее?

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +		rawBody, err := ioutil.ReadAll(r.Body)
тело реквеста, должно закрываться через defer

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +			_, _ = fmt.Fprint(w, Error.Wrap("invalid json", err))
мммм?

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +		err = credentials.UnmarshalJSON(rawBody)
` go
err = json.NewDecoder(resp.Body).Decode(&apiResp)
	if err != nil {
		return res, errors.Wrapf(err, "failed to unmarshal response")
	}
	resp.Body.Close()
`
например

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +		w.Header().Set("content-type", "application/json")
контент тайп с большой буквы, ты уверен, что он не проставляется автоматически?

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/handlers/main.go
> +		if updateUser.Name != "" {
switch {
case updateUser.Name != "":
case updateUser.Password != "":
}

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/images/main.go
> +const UploadUsersPath = "/Users/artyombakulev/Projects/2019_2_Pirogi/media/users/"
лучше использовать предназначенную для этого папку типа /var/www/media
и это у тебя не будет работать на другой тачке

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/images/main.go
> +	return target + "_" + userID + ending
хранить файлы с пользовательскими названиями нельзя

2019-09-28 16:03 UTC, Smet1 commented on internal/pkg/middleware/middleware.go
> +			if r.Method == http.MethodGet || r.Method == http.MethodPost && (r.URL.Path == "/api/users/" || r.URL.Path == "/api/login/") {
почему миддлвара должна это знать?

2019-09-28 20:18 UTC, Artefakt-ff commented on internal/pkg/inmemory/main.go
> +func (db *DB) Get(id int, t string) (interface{}, error) {
мы не знаем какой объект нам вернется

2019-09-29 10:58 UTC, Artefakt-ff commented on internal/pkg/auth/main.go
> +			return errors.New("db error while inserting cookie: " + err.Error())
я пока сделал свой пакет, потом перекочую на pkg/errors

2019-10-02 16:03 UTC, merged