Add MongoDB support
go-park-mail-ru/2019_2_Pirogi pull request #7
Opened 2019-10-19 15:04 UTC by lisa-bella97

Добавила реализацию функций для работы с MongoDB.

2019-10-21 21:50 UTC, Smet1 commented on cmd/server/main.go
> +	// conn.FakeFillDB()
есть такая штука once.Do

2019-10-21 21:51 UTC, Smet1 commented on configs/default.go
> +const MongoUser = ""
константы лучше так
const (
    MongoUser = "..."
)

2019-10-21 21:52 UTC, Smet1 commented on configs/default.go
> +const UserTargetName = "user"
это бы в конфиг
не гошный, а православный, типо yaml

2019-10-21 21:52 UTC, Smet1 commented on internal/pkg/auth/auth.go
> +	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
буэ
почему с большой буквы

2019-10-21 21:53 UTC, Smet1 commented on internal/pkg/auth/auth.go
> +			return Error.New(400, "invalid credentials")
http константы, они есть в пакете

2019-10-21 21:55 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
проверяйте каст переменных

2019-10-21 21:55 UTC, Smet1 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
(

2019-10-21 21:56 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	_, _ = conn.counters.InsertMany(conn.context, []interface{}{
а ошибку?

2019-10-21 21:56 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	_, _ = conn.counters.InsertMany(conn.context, []interface{}{
тут once.Do зайдет

2019-10-21 21:56 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	err := conn.counters.FindOneAndUpdate(conn.context, bson.M{"_id": target},
лучше оборачивать ошибку
потом будет тяжело найти источник

2019-10-21 21:57 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +		_, _ = conn.cookies.DeleteOne(conn.context, bson.M{"_id": u.ID})
почему игнорируете?

2019-10-21 22:02 UTC, Smet1 requested changes

2019-10-21 22:02 UTC, Smet1 commented on cmd/server/main.go
> +	// conn.FakeFillDB()
есть такая штука once.Do

2019-10-21 22:02 UTC, Smet1 commented on configs/default.go
> +const MongoUser = ""
константы лучше так
const (
MongoUser = "..."
)

2019-10-21 22:02 UTC, Smet1 commented on configs/default.go
> +const UserTargetName = "user"
это бы в конфиг
не гошный, а православный, типо yaml

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/auth/auth.go
> +	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
буэ
почему с большой буквы?

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/auth/auth.go
> +			return Error.New(400, "invalid credentials")
http константы, они есть в пакете

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
проверяйте каст переменных

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
(((((

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	_, _ = conn.counters.InsertMany(conn.context, []interface{}{
а ошибку?

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	_, _ = conn.counters.InsertMany(conn.context, []interface{}{
тут once.Do зайдет

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +	return result.Seq, err
лучше оборачивать ошибку
потом будет тяжело найти источник

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +		_, _ = conn.cookies.DeleteOne(conn.context, bson.M{"_id": u.ID})
почему игнорируете?

2019-10-21 22:02 UTC, Smet1 commented on scripts/run_production.sh
>  docker volume create log
можете использовать docker-compose, там все это есть

2019-10-21 22:02 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +func InitInmemory() *InmemoryDB {
кстати, зачем вам этот пакет?

2019-10-23 07:00 UTC, lisa-bella97 commented on internal/pkg/auth/auth.go
> +	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
потому что тогда стандартный пакет ошибок перекрывается и его нельзя будет использовать в этом файле

2019-10-23 08:08 UTC, lisa-bella97 commented on cmd/server/main.go
> +	// conn.FakeFillDB()
перенесла в отдельный файл

2019-10-23 08:09 UTC, lisa-bella97 commented on configs/default.go
> +const MongoUser = ""
fix

2019-10-23 08:19 UTC, lisa-bella97 commented on internal/pkg/auth/auth.go
> +			return Error.New(400, "invalid credentials")
fix

2019-10-23 08:19 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
> +	_, _ = conn.counters.InsertMany(conn.context, []interface{}{
fix

2019-10-23 08:20 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +func InitInmemory() *InmemoryDB {
не нужен, пусть пока будет

2019-10-24 20:37 UTC, lisa-bella97 commented on configs/default.go
> +const UserTargetName = "user"
fix

2019-10-24 21:20 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
с маленькой тут нельзя заменить, так как в файле используется еще стандартный пакет error

2019-10-24 21:20 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
с маленькой тут нельзя заменить, так как в файле используется еще стандартный пакет error

2019-10-24 21:22 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
в каждом кейсе проверять `in` на `nil`?

2019-10-24 21:38 UTC, lisa-bella97 commented on internal/pkg/auth/auth.go
> +	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
но впрочем, здесь можно заменить

2019-10-24 21:38 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
> +	return result.Seq, err
fix

2019-10-24 21:39 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
> +		_, _ = conn.cookies.DeleteOne(conn.context, bson.M{"_id": u.ID})
fix

2019-10-25 08:38 UTC, Smet1 requested changes

2019-10-25 08:38 UTC, Smet1 commented on cmd/database/initDB.go
> +	"github.com/labstack/gommon/log"
Вам про логгер не рассказывали еще?

2019-10-25 08:38 UTC, Smet1 commented on cmd/database/initDB.go
> +	conn.ClearDB()
Безусловная очистка базы, не оч. Вдруг вы решили рестартануть бэк, а у вас все дропнулось

2019-10-25 08:38 UTC, Smet1 commented on cmd/server/main.go
> +	file, err := ioutil.ReadFile("../../configs/default.yaml")
Относительные пути, давайте нормальные или из аргументов бинаря

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/database/inmemory.go
>  // затирает старые записи
Может сделаете нормальные комменты?
И если она затирает старые записи, почему insert?

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/auth/auth.go
>  func Login(ctx echo.Context, db database.Database, email, password string) *models.Error {
Почему не context.Context?

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/auth/auth.go
>  func LoginCheck(_ http.ResponseWriter, r *http.Request, db database.Database) bool {
Если вы не используете response, тогда зачем он в аргументах?

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +func (db *InmemoryDB) GetIDForInsert(target string) int {
Вы не могновские айди используете?

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
На ok. Только после него работаете с переменной

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/database/inmemory.go
> +		Path:  "/",
Внесите это в конфиг, будет удобнее

2019-10-25 08:38 UTC, Smet1 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
Что? Почему и зачем

2019-10-26 10:15 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +	switch in := in.(type) {
так switch в случае !ok пойдет к следующему case и так до default

2019-10-26 10:31 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
потому что models.Error используются там, где нужно послать ответ клиенту, а в случае ошибки инициализации коннекшена с БД (например) наш бек просто не запускается дальше, ибо это фатальная ошибка

2019-10-26 10:31 UTC, lisa-bella97 commented on internal/pkg/database/mongo.go
>  	Error "github.com/go-park-mail-ru/2019_2_Pirogi/internal/pkg/error"
и в этих случаях используется обычная ошибка

2019-10-26 14:39 UTC, lisa-bella97 commented on cmd/database/initDB.go
> +	conn.ClearDB()
так мы этот файл запускаем только один раз, чтобы проинициализировать базу фейковыми данными (рестарт бэка базу никак не тронет)

2019-10-26 14:39 UTC, lisa-bella97 commented on cmd/database/initDB.go
> +	conn.ClearDB()
и чтобы инициализация прошла корректно, на всякий случай сначала чистим базу

2019-10-26 14:56 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +func (db *InmemoryDB) GetIDForInsert(target string) int {
это inmemory

2019-10-26 15:03 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
>  // затирает старые записи
fix

2019-10-26 15:04 UTC, lisa-bella97 commented on internal/pkg/auth/auth.go
>  func LoginCheck(_ http.ResponseWriter, r *http.Request, db database.Database) bool {
fix

2019-10-26 15:04 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
> +		Path:  "/",
в конфиге уже есть имя куки

2019-10-26 19:27 UTC, lisa-bella97 commented on scripts/run_production.sh
>  docker volume create log
fix

2019-10-27 08:30 UTC, lisa-bella97 commented on cmd/server/main.go
> +	file, err := ioutil.ReadFile("../../configs/default.yaml")
fix

2019-10-27 08:31 UTC, lisa-bella97 commented on internal/pkg/auth/auth.go
>  func Login(ctx echo.Context, db database.Database, email, password string) *models.Error {
вопрос к Артему:)

2019-10-27 09:17 UTC, Smet1 approved these changes

2019-10-27 11:56 UTC, merged