Docker
go-park-mail-ru/2019_2_Pirogi pull request #9
Opened 2019-10-20 19:59 UTC by Artefakt-ff

2019-10-31 20:56 UTC, Smet1 commented on docker-compose.yaml
> +      - MONGO_INITDB_USERNAME=cinsear-user
вот эти штуки было бы неплохо не хранить в репе

2019-10-31 21:02 UTC, Smet1 requested changes

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/auth/auth.go
> +	expiration := time.Now().Add(configs.Default.CookieAuthDurationHours * time.Hour)
а если захотите не часы?
придется менять код
мб добавите возможность писать в конфиг единицы измерения, например, '10s' или '100500h'

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/database/inmemory.go
>  	"strconv"
его же вроде хотели удалить?

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/database/inmemory.go
>  	"strconv"
пакет inmemory

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +func (conn *MongoConnection) InsertOrUpdate(in interface{}) *models.Error {
upsert

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/database/mongo.go
> +func (conn *MongoConnection) InsertOrUpdate(in interface{}) *models.Error {
такая функция в монге есть

2019-10-31 21:02 UTC, Smet1 commented on internal/pkg/handlers/sessions.go
> +			return echo.NewHTTPError(401, "no auth")
константы

2019-11-01 09:47 UTC, lisa-bella97 commented on internal/pkg/database/inmemory.go
>  	"strconv"
в следующем мр (на другой ветке удалили)

2019-11-04 14:56 UTC, Smet1 approved these changes

2019-11-04 16:36 UTC, merged